site_name: V1 Engineering Inc Docs

repo_name: V1EngineeringInc/V1EngineeringInc-Docs
repo_url: https://github.com/V1EngineeringInc/V1EngineeringInc-Docs/
edit_uri: 'tree/master/docs/'

nav:
 - Index: index.md
 - Editing mkdocs: mkdocs_info.md
 - MPCNC:
     - Assembly:
         - Step1: pg1.md
         - 3-Corners, Rollers, Base: MPCNC_Assm3_CRB.md
     - Electronics:
         - Step2: pg2.md
     - Madness:
         - Plasma Stuff:
            - plasma3: pg3.md
 - LowRider:
     - Assembly: pg4.md
 - ZenXY: ZenXY.md

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'red'
  # This actually works with material
  # logo: "https://www.v1engineering.com/wp-content/uploads/2017/12/V1-Engineering-logo-260wide.png"
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"

extra:
  social:
    - type: 'globe'
      link: 'https://v1engineering.com'
    - type: 'shopping-cart'
      link: 'https://shop.v1engineering.com'

extra_css: [v1.css]

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

copyright: "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/legalcode\">CC-BY-SA</a> Copyright 2019 V1Engineering Inc."

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pyembed.markdown
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - sane_lists
  - smarty
  - toc:
      permalink: true
  - lightgallery
  - pymdownx.extra

