version: 2.1
jobs:
  build:
    docker:
     - image: circleci/python:3.6-jessie-browsers
    steps:
     - checkout
     - run: sudo pip install -r requirements.txt
     - run: mkdocs build --clean --strict
